### ISSUE TITLE
Error while building the files .

### ISSUE THREAD

**Issue by charvi-077** [WestTeam/CoreSLAM#2]
I am running as per the readme files but while building the files , I am getting following error .
My cmake version - 3.10.2

/home/charvi/core_Slam/CoreSLAM/src/State.cpp:88:20: error: ‘class WestBot::CoreSLAM::RobotParameters’ has no member named ‘r’
         m = params.r * M_PI / params.inc;
                    ^
/home/charvi/core_Slam/CoreSLAM/src/State.cpp:94:79: error: ‘class WestBot::CoreSLAM::RobotParameters’ has no member named ‘R’
  = (m * ((sd->q2 - q2) * params.ratio() - sd->q1 + q1) / params.R) * 180 / M_PI;
                                                                 ^
/home/charvi/core_Slam/CoreSLAM/src/State.cpp:99:16: warning: operation on ‘psidot’ may be undefined [-Wsequence-point]
         psidot = psidot = 0;
         ~~~~~~~^~~~~~~~~~~~
/home/charvi/core_Slam/CoreSLAM/src/State.cpp:100:11: warning: operation on ‘v’ may be undefined [-Wsequence-point]
         v = v = 0;
         ~~^~~~~~~
CMakeFiles/CoreSLAM.dir/build.make:158: recipe for target 'CMakeFiles/CoreSLAM.dir/src/State.cpp.o' failed
make[2]: *** [CMakeFiles/CoreSLAM.dir/src/State.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CoreSLAM.dir/all' failed
make[1]: *** [CMakeFiles/CoreSLAM.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JeremySavonet** [comment]
You can check the branch linked in the issue to see if it fix the build:
https://github.com/WestTeam/CoreSLAM/tree/build-error%232-charvi-077

Regards,

**Comment by JeremySavonet** [comment]
Let me know if it fix your issue and I'll close it and merge the branch into master

**Comment by charvi-077** [comment]
Yes , the branch fixes the issue .  Thank you !
